on:
  push:


name: "Have a ğŸª"

jobs:
  CI:
    runs-on: ubuntu-latest
    name: "cookie"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/humans.txt@2349eb5872154ed910e63d9e18b24ab57a4a05a4
        with:
          format: txt
      - uses: actions/humans.txt@2349eb5872154ed910e63d9e18b24ab57a4a05a4
        with:
          format: shell
      - uses: actions/humans.txt@2349eb5872154ed910e63d9e18b24ab57a4a05a4
        with:
          format: json
