on:
  push:


name: "Have a ğŸª"

jobs:
  CI:
    runs-on: ubuntu-latest
    name: "cookie"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/humans.txt@v1
        with:
          format: txt
      - uses: actions/humans.txt@v1
        with:
          format: shell
      - uses: actions/humans.txt@v1
        with:
          format: json
